scalar Id
scalar Text
scalar BigIntVP
scalar BigDecimalVP

type TokenHolder {
  id: String!
  delegate: Delegate
  tokenBalanceRaw: BigIntVP!
  tokenBalance: BigDecimalVP!
  totalTokensHeldRaw: BigIntVP!
  totalTokensHeld: BigDecimalVP!
}

type Delegate {
  id: String!
  delegatedVotesRaw: BigIntVP!
  delegatedVotes: BigDecimalVP!
  tokenHoldersRepresentedAmount: Int!
  tokenHoldersRepresented: [TokenHolder]! @derivedFrom(field: "delegate")
  delegateProfile: [DelegateProfile]! @derivedFrom(field: "delegateId")
}

type Governance {
  id: String!
  currentTokenHolders: Int!
  currentDelegates: Int!
  totalTokenHolders: Int!
  totalDelegates: Int!
  delegatedVotesRaw: BigIntVP!
  delegatedVotes: BigDecimalVP!
}

type DelegateProfile {
    id: String!
    delegateId: String!
    statement: String!
    interests: String
    twitter: String
    github: String
    telegram: String
    discord: String
    createdAt: String!
    updatedAt: String!
}